### ISSUE TITLE
example code for reading SPI

### ISSUE THREAD

**Issue by tonyt321** [Gigahawk/clickwheel_reverse_eng#1]
i am trying to read the SPI data using a arduino
not sure as all i am getting are zeros as an output
[New Text Document.txt](https://github.com/Gigahawk/clickwheel_reverse_eng/files/8189622/New.Text.Document.txt)

**Comment by Gigahawk** [comment]
Please actually read the readme.

Pinout for the 4th gen clickwheel is provided by https://jasongarr.wordpress.com/project-pages/ipod-clickwheel-hack/

Verify with a logic analyzer before you attempt to write code for it.
